CREATE TABLE IF NOT EXISTS messages (
    serial_number SERIAL PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    latitude  DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE USER admin WITH ENCRYPTED PASSWORD 'securepassword';
GRANT ALL PRIVILEGES ON DATABASE messages_db TO admin;
GRANT ALL PRIVILEGES ON TABLE messages TO admin;