services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    ports:
      - "${BACKEND_PORT_PRODUCER}:${BACKEND_PORT_PRODUCER}"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default

  writer:
    build:
      context: .
      dockerfile: Dockerfile-writer
    ports:
      - "${BACKEND_PORT_WRITER}:${BACKEND_PORT_WRITER}"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default

  dev:
    build:
      context: .
      dockerfile: Dockerfile-writer
    ports:
      - "7425:7425"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default

  # database
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default

# Development Network
networks:
  default:
    driver: bridge