services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    ports:
      - "${BACKEND_PORT_PRODUCER}:${BACKEND_PORT_PRODUCER}"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - default

  writer:
    build:
      context: .
      dockerfile: Dockerfile-writer
    ports:
      - "${BACKEND_PORT_WRITER}:${BACKEND_PORT_WRITER}"
    env_file:
      - .env
    depends_on:
      - producer
    networks:
      - default

  dev:
    build:
      context: .
      dockerfile: Dockerfile-writer
    ports:
      - "7425:7425"
    env_file:
      - .env
    depends_on:
      - producer
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
    depends_on:
      - postgres
    networks:
      - default  

  # database
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default

# Development Network
networks:
  default:
    driver: bridge